# Generated by Django 5.1.6 on 2025-02-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix', '0002_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myflix.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myflix.user')),
            ],
        ),
    ]
